django_data_disks_test/api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register('disks', views.DiskViewSet)
# router.register('disks', views.DiskList)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

django_data_disks_test/disk_manager/urls.py
from django.urls import path

from . import views  # import views so we can use them in urls.


urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path('add/', views.edit, name='add'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

django_data_disks_test/django_data_disks_test/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from disk_manager import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('', views.index, name='index'),
    path('disk/', include(('disk_manager.urls', 'disk_manager'), namespace='disk_manager')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

django_data_disks_test/user/urls.py
from django.urls import path

from user import views


urlpatterns = [
    path('connexion', views.connexion, name='connexion'),
    path('deconnexion', views.deconnexion, name='deconnexion'),
]

django_data_disks_test/api/models.py
# from django.db import models

django_data_disks_test/disk_manager/models.py
from enum import Enum
from django.db import models
from django.conf import settings


class DiskBrand(Enum):
    TOSHIBA = "Toshiba"
    SEAGATE = "Seagate"
    SANDISK = "SanDisk"
    WD = "Western Digital"


class DiskType(Enum):
    SSD = "SSD"
    SSHD = "SSHD"
    HDD_2 = "HDD 2'5"
    HDD_3 = "HDD 3'5"


class Disk(models.Model):
    serial_number = models.CharField(max_length=255)
    type = models.CharField(
      max_length=15,
      choices=[(tag.value, tag.value) for tag in DiskType]
    )
    brand = models.CharField(
      max_length=15,
      choices=[(tag.value, tag.value) for tag in DiskBrand]
    )
    price = models.DecimalField(max_digits=15, decimal_places=2)  # in €
    quantity = models.IntegerField()
    size = models.IntegerField()  # in Go
    speed = models.IntegerField()  # unit is MB/s
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

django_data_disks_test/user/models.py
# from django.db import models

# Create your models here.

django_data_disks_test/disk_manager/forms.py
from django.forms import ModelForm
from disk_manager.models import Disk


class DiskForm(ModelForm):
    class Meta:
        model = Disk
        fields = ('serial_number', 'type', 'brand', 'price', 'size', 'speed', 'quantity',)

django_data_disks_test/user/forms.py
from django import forms


class ConnexionForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)

django_data_disks_test/api/views.py
from rest_framework import viewsets, status
from rest_framework.response import Response
# from rest_framework import generics
from django_filters.rest_framework import DjangoFilterBackend

from .serializers import DiskSerializer
from disk_manager.models import Disk


class DiskViewSet(viewsets.ModelViewSet):
    queryset = Disk.objects.all().order_by('id')
    filter_backends = [DjangoFilterBackend]
    serializer_class = DiskSerializer
    filter_fields = ('user',)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def create(self, request):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(user=request.user)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    def update(self, request, pk=None):
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=False)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def destroy(self, request, pk=None):
        instance = self.queryset.filter(id=pk)
        instance.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

# class DiskList(generics.ListAPIView):
#     serializer_class = DiskSerializer

#     def get_queryset(self):
#         """
#         This view should return a list of all the purchases
#         for the currently authenticated user.
#         """
#         user = self.request.user
#         return Disk.objects.filter(purchaser=user).order_by('id')

django_data_disks_test/disk_manager/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.db.models import Sum
from django.db.models import F
from disk_manager.forms import DiskForm
from disk_manager.models import Disk
from disk_manager.models import DiskType


def index(request):
    user = request.user
    if user.is_authenticated:
        # filter user disks and add a column with line price (quantity x disks number)
        disks = Disk.objects.filter(user=request.user).order_by('id').annotate(line_price=F('price') * F('quantity'))

        # count value by disk type
        total_by_type = {}
        for current_type in DiskType:
            disks_by_type = disks.filter(type=current_type.value)
            # we count only existing values
            if(disks_by_type.count() != 0):
                total_by_type[current_type.value] = {
                    'total_price': str(disks_by_type.aggregate(sum=Sum('line_price'))['sum']),
                    'disks_quantity': str(disks_by_type.aggregate(sum=Sum('quantity'))['sum']),
                }

        for type, total in total_by_type.items():
            print(f"{type}: {total['total_price']}€, {total['disks_quantity']} disks")

        data = {
            'disks': disks,
            'total_by_type': total_by_type,
            'total_price': str(disks.aggregate(sum=Sum('line_price'))['sum']),
            'disks_quantity': str(disks.aggregate(sum=Sum('quantity'))['sum']),
        }
        return render(request, 'disk_manager/index.html', data)
    else:
        return redirect('user/connexion')


def edit(request, id=None):
    if id:
        member = get_object_or_404(Disk, pk=id)  # load object
    else:
        member = Disk()  # or create new
    if request.method == 'POST':  # when POST request
        form = DiskForm(request.POST, instance=member)  # generate form
        if form.is_valid():  # record if validation is OK
            disk = form.save(commit=False)
            disk.user = request.user
            disk.save()
            return redirect('disk_manager:index')
        else:
            error = form.errors
            print(error)
    else:  # when GET method
        form = DiskForm(instance=member)  # generate form
    return render(request, 'disk_manager/edit.html', dict(form=form, id=id))  # display new or edit page


def delete(request, id):
    # return HttpResponse("Effacer")
    disk = get_object_or_404(Disk, pk=id)
    disk.delete()
    return redirect('disk_manager:index')


def detail(request, id=None):
    return HttpResponse("Détails")

django_data_disks_test/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .forms import ConnexionForm


def connexion(request):
    error = False
    if request.method == "POST":
        form = ConnexionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)  # Nous vérifions si les données sont correctes
            if user:  # Si l'objet renvoyé n'est pas None
                login(request, user)  # nous connectons l'utilisateur
                return redirect('/')
            else:  # sinon une erreur sera affichée
                error = True
    else:
        form = ConnexionForm()

    return render(request, 'login.html', locals())


def deconnexion(request):
    logout(request)
    return redirect('/')

django_data_disks_test/disk_manager/templates/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'store/css/disks.css' %}" /> -->
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
          <div class="col-sm-offset-2 col-sm-10">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">

                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="{% url 'disk_manager:index' %}">Gestion de disques</a>
            </div>
            <div style="float: right;">
                <a class="navbar-brand" style="float: right;" href="{% url 'user:deconnexion' %}">Déconnection</a>
            </div>
          </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'disk_manager:index' %}">Tous vos disques</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </nav>

    <!-- content -->
    <div class="container">
        <div class="row">
          <div class="box">
            {% block content %}{% endblock %}
          </div>
        </div>
      </div>

    <!-- footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; <a href="https://www.linkedin.com/in/gwendal-toullec/" target="_blank">Gwendal TOULLEC</a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>

  </body>
</html>

django_data_disks_test/disk_manager/templates/disk_manager/detail.html
{% extends 'store/base.html' %}

{% block content %}
<hr>
<h1 class="intro-text text-center">{{ album_title }}</h1>
<hr class="detail-separator">
<div class="col-md-6">
  <img src="{{ thumbnail }}" alt="{{ album_title }}" class="img-responsive">
</div>
<div class="col-md-6">
  <div style="margin-bottom:45px">
    <h2 class="text-center artist_name">Artistes</h2>
    <p>{{ artists_name }}</p>
  </div>
  <h2 class="text-center artist_name">Réserver {{ album_title }}</h2>
  <p style="margin-bottom: 20px;">Demandez-nous de mettre de côté {{ album_title }} et venez le chercher dès demain en magasin ! </p>
  <form class="form-inline" action="{% url 'store:detail' album_id=album_id %}" method="post">
    {% csrf_token %}
    <div class="form-group  {% if form.name.errors %}has-warning has-feedback{% endif %}">
    <!--
      <label for="name" class="control-label">Nom</label>
      <input type="text" name="name" value="" id="name">
      -->
      <label for="{{ form.name.id_for_label }}">
      {{ form.name }}
    </div>
    <div class="form-group {% if form.email.errors %}has-warning has-feedback{% endif %}">
    <!--
      <label for="email" class="control-label">E-mail</label>
      <input type="text" name="email" value="" id="email">
      -->
      <label for="{{ form.email.id_for_label }}">
      {{ form.email }}
    </div>
    <!-- <input type="hidden" class="hidden" value="{{ album_id }}" name="album_id"> -->
    <button type="submit" class="btn btn-success">Réserver</button>
    {{form.errors}}
  </form>
</div>
{% endblock %}
{% if errors %}
<div>
  {% for key, error in errors %}
  {% autoescape off %}
    {{ error }}
  {% endautoescape %}
  {% endfor %}
</div>
{% endif %}

django_data_disks_test/disk_manager/templates/disk_manager/edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
    {% if id %}
    <h3 class="page-header" style="text-align:center">Modification des disques</h3>
    <form action="{% url 'disk_manager:edit' id=id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <h3 class="page-header" style="text-align:center">Enregistrement des disques</h3>
    <form action="{% url 'disk_manager:add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div style="margin-top: 5px;">
            <button type="submit" class="btn btn-primary">Envoyer</button>
          </div>
          <br />
          <div style="float: right; margin-top: 5px;">
            <a href="{% url 'disk_manager:index' %}" class="btn btn-primary">Annuler</a>
          </div>
        </div>
      </div>
    </form>
{% endblock content %}

django_data_disks_test/disk_manager/templates/disk_manager/index.html
{% extends "base.html" %}

{% block content %}
<h3 style="text-align: center;">Affichage de la liste</h3>
<div style="float: right; margin-bottom: 5px;;">
    <a href="{% url 'disk_manager:add' %}" class="btn btn-primary btn-sm">ajouter à</a>
</div>
<div>
    <h4>Récap Total:  </h4>
    {{ total_price }}€, {{ disks_quantity }} disques
</div>
<div>
    <h4>Récap par type de disque:</h4>
    {% for type, total in total_by_type.items %}
        {{type}}: {{ total.total_price }}€, {{total.disks_quantity }} disques <br />
    {% endfor %}
</div>
<br />
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>type</th>
            <th>serial number</th>
            <th>brand</th>
            <th>price</th>
            <th>size</th>
            <th>speed</th>
            <th>user</th>
            <th>quantity</th>
        </tr>
    </thead>
    <tbody>
        {% for disk in disks %}
        <tr>
            <td>{{ disk.type }}</td>
            <td><a href="{% url 'disk_manager:detail' id=disk.id %}">{{ disk.serial_number }}</a></td>
            <td>{{ disk.brand }}</a></td>
            <td>{{ disk.price }}</td>
            <td>{{ disk.size }} (Go)</a></td>
            <td>{{ disk.speed }} (MB/s)</a></td>
            <td>{{ disk.user }}</td>
            <td>{{ disk.quantity }}</td>
            <td>
                <a href="{% url 'disk_manager:edit' id=disk.id %}" class="btn btn-primary btn-sm">Éditer</a>
                <a href="{% url 'disk_manager:delete' id=disk.id %}" class="btn btn-primary btn-sm" id="btn_del">Effacer</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

{% block script %}
{% endblock %}

django_data_disks_test/user/templates/login.html
<h1>Se connecter</h1>

{% if error %}
<p><strong>Utilisateur inexistant ou mauvais de mot de passe.</strong></p>
{% endif %}

{% if user.is_authenticated %}
Vous êtes connecté, {{ user.username }} !
{% else %}
<form method="post" action="connexion">
       {% csrf_token %}
       {{ form.as_p }}
    <input type="submit"/>
</form>
{% endif %}